// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// Copywright © 2026 ZenithClown (Debmalya Pramanik) | https://zenithclown.github.io/ | https://www.linkedin.com/in/dpramanik/
//
//@version=6
//
// ==================================================================
// OBJECTTIVE: Create a Regression Channel & Forward Forecast
//
// Check https://github.com/finofunda/fincy for additional details.
// Check https://in.tradingview.com/u/ZenithClown/ for TV Profile.
// ==================================================================

indicator(
    'Regression Channel'
    // Overlay the bands over the original chart, main objective
    , overlay = true
)

// ------------------------------------------------------------------
// INPUT(s) for Regression Channel Calculation(s)
// ------------------------------------------------------------------

regressionType = input.string(
    'linear', 'Regression Type'
    , options = [
        'linear', 'exponential', 'polynomial'
    ]
)

dataSource = input.source(close, 'Data Source')

// Lookback and Forecast Period Settings

lookbackPeriod = input.int(
    100, 'Lookback Period (No. of Candels)', minval = 2, step = 1
    , group = 'Model Settings'
    , tooltip = 'Setting a value >= 5000 may result in a slow performance.'
)

// Channel Settings, allow dynamic upper and lower channel controls

showUpperChannel = input.bool(
    true, 'Show Upper Deviation Channel'
    , group = 'Channel Settings', inline = 'Upper Channel'
)

upperChannelDeviation = input.float(
    2.0, '', active = showUpperChannel, step = 0.1
    , group = 'Channel Settings', inline = 'Upper Channel'
)
showLowerChannel = input.bool(
    true, 'Show Lower Deviation Channel'
    , group = 'Channel Settings', inline = 'Lower Channel'
)

lowerChannelDeviation = input.float(
    2.0, '', active = showLowerChannel, step = 0.1
    , group = 'Channel Settings', inline = 'Lower Channel'
)

nTopBottom = input.int(
    2, 'No. of Channel(s) from Mean Line', minval = 1, maxval = 4, step = 1
    , tooltip = 'Create multiple channels to understand market range.'
    , group = 'Channel Settings'
)

// ------------------------------------------------------------------
// Display Setting(s) for Forecast Period & Color(s)
//
// Display settings are defined of two types - general settings which
// are applicable for all (ex. color settings) and regression model
// specific settings. Check the group names for more details.
// ------------------------------------------------------------------

isLinearModel = switch regressionType
    'linear' => true
    => false

showPearsonInput = input.bool(
    true, 'Show Pearsons R', active = isLinearModel
    , group = 'Display Settings (Linear Model)'
)

extendLeftInput = input.bool(
    false, 'Extend Left Lines', active = isLinearModel
    , group = 'Display Settings (Linear Model)'
    , tooltip = 'Extend to check when there was a reversal.'
)

extendRightInput = input.bool(
    true, 'Extend Right Lines', active = isLinearModel
    , group = 'Display Settings (Linear Model)'
    , tooltip = 'Extend to check potential market movement.'
)

linRegExtendType = switch
    extendLeftInput and extendRightInput => extend.both
    extendLeftInput => extend.left
    extendRightInput => extend.right
    => extend.none

// General Display - Color Settings

colorUpperChannel = input.color(
    color.new(color.green, 85), ''
    , group = 'Display Settings', inline = 'Display Settings'
)

colorLowerChannel = input.color(
    color.new(color.red, 85), ''
    , group = 'Display Settings', inline = 'Display Settings'
)

// ------------------------------------------------------------------
// Function(s)/Calculation(s) for Linear Regression & Deviation
//
// linearRegression - Function to calculate linear regression values,
// namely the slope and intercept. The function uses `barstate.islast`
// to prevent the model to recalculate on every candel (thus reducing
// unnecessary load time) and calculates only when we've reached the
// end of the loop.
// ------------------------------------------------------------------

linearRegression(source, length) =>
    if not barstate.islast
        [float(na), float(na), float(na)]
    else
        sumX = 0.0
        sumY = 0.0
        sumXY = 0.0
        sumXSqr = 0.0

        for i = 0 to length - 1 by 1
            value = source[i]
            perct = i + 1.0

            sumX += perct
            sumY += value
            sumXY += perct * value
            sumXSqr += math.pow(perct, 2)

        slope = (length * sumXY - sumX * sumY) / (length * sumXSqr - math.pow(sumX, 2))

        average = sumY / length
        intercept = average - slope * sumX / length + slope

        [slope, average, intercept]


linearDeviation(source, length) =>
    lrc0 = ta.linreg(source, length, 0)
    lrc1 = ta.linreg(source, length, 1)

    lrcSlope = lrc0 - lrc1
    lrcIntercept = lrc0 - bar_index * lrcSlope

    deviationSum = 0.0
    for z = 0 to length - 1 by 1
        deviationSum := deviationSum + math.pow(source[z] - (lrcSlope * (bar_index - z) + lrcIntercept), 2)

    deviation = math.sqrt(deviationSum / length)
    [deviation]

// ------------------------------------------------------------------
// Visualization of Regression, Forecast & Top/Bottom Bounds
// ------------------------------------------------------------------

[slope, average, intercept] = linearRegression(dataSource, lookbackPeriod)

// ? Calculate the start and end price of the mean regression line
startPriceLinReg = intercept + slope * (lookbackPeriod - 1)
endPriceLinReg = intercept

var line meanLineLinReg = na
if na(meanLineLinReg) and not na(startPriceLinReg)
    meanLineLinReg := line.new(
        bar_index - lookbackPeriod + 1, startPriceLinReg, bar_index, endPriceLinReg
        , width = 1, extend = linRegExtendType, color = color.new(colorLowerChannel, 0)
    )
else
    line.set_xy1(meanLineLinReg, bar_index - lookbackPeriod + 1, startPriceLinReg)
    line.set_xy2(meanLineLinReg, bar_index, endPriceLinReg)
